# Generated by Django 5.2.5 on 2025-08-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('absences', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
